# Generated by Django 2.0 on 2019-02-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='name_select',
            field=models.CharField(default='area', max_length=32),
        ),
    ]
